package utils_test

import (
	"go/ast"
	"go/token"
	"runtime"
	"testing"

	"github.com/stretchr/testify/assert"

	"policycheck/internal/policycheck/utils"
)

func TestNormalizePolicyPath(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		value string
		want  string
	}{
		{name: "empty path", value: "", want: ""},
		{name: "current directory", value: ".", want: ""},
		{name: "dot prefix", value: "./internal/policycheck", want: "internal/policycheck"},
		{name: "windows separators", value: `internal\policycheck\..\tests`, want: "internal/tests"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tt.want, utils.NormalizePolicyPath(tt.value))
		})
	}
}

func TestHasPrefix(t *testing.T) {
	t.Parallel()

	assert.True(t, utils.HasPrefix("internal/policycheck/core", []string{"internal/policycheck"}))
	assert.True(t, utils.HasPrefix("internal/policycheck", []string{"./internal/policycheck"}))
	assert.False(t, utils.HasPrefix("internal/policychecker", []string{"internal/policycheck"}))
	assert.False(t, utils.HasPrefix("cmd/policycheck", []string{""}))
}

func TestToSlashRel(t *testing.T) {
	t.Parallel()

	assert.Equal(t, "internal/policycheck/utils/utils.go", utils.ToSlashRel(
		`C:\repo`,
		`C:\repo\internal\policycheck\utils\utils.go`,
	))

	if runtime.GOOS == "windows" {
		assert.Equal(t, "D:/other/place/file.go", utils.ToSlashRel(
			`C:\repo`,
			`D:\other\place\file.go`,
		))
	}

	assert.Equal(t, "internal/policycheck/utils/utils.go", utils.ToSlashRel(
		`C:\repo`,
		"./internal/policycheck/utils/utils.go",
	))
}

func TestPluralizeVerb(t *testing.T) {
	t.Parallel()

	assert.Equal(t, "has", utils.PluralizeVerb("has", 1))
	assert.Equal(t, "have", utils.PluralizeVerb("has", 2))
	assert.Equal(t, "do", utils.PluralizeVerb("does", 2))
	assert.Equal(t, "run", utils.PluralizeVerb("runs", 2))
	assert.Equal(t, "build", utils.PluralizeVerb("build", 2))
}

func TestIsGeneratedFile(t *testing.T) {
	t.Parallel()

	assert.True(t, utils.IsGeneratedFile([]byte("// Code generated by test. DO NOT EDIT.\n")))
	assert.False(t, utils.IsGeneratedFile([]byte("// handwritten file\n")))
}

func TestSelectorBaseName(t *testing.T) {
	t.Parallel()

	assert.Equal(t, "receiver", utils.SelectorBaseName(&ast.Ident{Name: "receiver"}))
	assert.Equal(t, "Method", utils.SelectorBaseName(&ast.SelectorExpr{
		X:   &ast.Ident{Name: "receiver"},
		Sel: &ast.Ident{Name: "Method"},
	}))
	assert.Equal(t, "", utils.SelectorBaseName(&ast.BasicLit{Kind: token.STRING, Value: `"value"`}))
}
